APP_NAME="Yachtlieger Achterwasser Test"
APP_KEY=
APP_ENV=testing
APP_DEBUG=false
APP_DEBUG_BAR=false
USE_CACHE=false
APP_URL=http://port.test
MIX_API_URL=http://port.test

NEXMO_KEY=
NEXMO_SECRET=

DB_CONNECTION=testing

DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=port_test
DB_USERNAME=root
DB_PASSWORD=root

DB_HOST_TEST=127.0.0.1
DB_PORT_TEST=3306
DB_DATABASE_TEST=port_test
DB_USERNAME_TEST=root
DB_PASSWORD_TEST=root

EXCEPTION_TO_EMAIL_ADDRESS=engels@goldenacker.de
EXCEPTION_FROM_EMAIL_ADDRESS=engels@goldenacker.de
EXCEPTION_EMAIL_SUBJECT="${APP_NAME} Error"

MONTH_SAISON_START=6 # Juni
MONTH_SAISON_END=9 # September
CARAVAN_PRICE_ELECTRIC_PER_DAY=2
CARAVAN_PRICE_ADDITIONAL_PERSONS_PER_DAY=1
CARAVAN_PRICE_PERSONS_INCLUSIVE=2
CARAVAN_PRICE_DEFAULT='{"4":12, "5":12, "6":12, "7":12, "8":12, "9":12, "10":12, "11":12, "12":12}'
CARAVAN_FALLBACK_PRICE_DEAULT=12

CARAVAN_PRICE_SAISON='{"4":15, "5":15, "6":15, "7":15, "8":15, "9":15, "10":15, "11":15, "12":15}'
CARAVAN_FALLBACK_PRICE_SAISON=15

DEFAULT_COUNTRY_ID=55
PAGINATIN_LIMIT=20
CUSTOMER_TYPES='{"guest": "Gast", "permanent": "Dauerlieger"}'
BOAT_TYPES='{"motor": "Motorboot", "sail": "Segelboot"}'
BOAT_DATES_MODI='{"": "Art wählen", "saison": "Sommerliegeplatz", "winter": "Winterlager"}'

BOAT_GUEST_PRICE_PER_METER=1.5
BOAT_GUEST_PRICE_ELECTRIC_PER_DAY=0
BOAT_GUEST_PRICE_ADDITIONAL_PERSONS_PER_DAY=0
BOAT_GUEST_PRICE_PERSONS_INCLUSIVE=0

BOAT_PRICE_SAISON_FACTOR=25.75
BOAT_PRICE_WINTER_FACTOR=15
# monat-tag
BOAT_SAISON_START="05-01"
BOAT_SAISON_END="10-31"
BOAT_WINTER_START="11-01"
BOAT_WINTER_END="04-30"
BOAT_CRANE_PRICE_PER_TON=20
BOAT_CRANE_MAST_PRICE=20
BOAT_CRANE_MAST_PRICE_UPPER_PER_100KG=10
BOAT_CLEANING_PRICE_PER_LENGTH_METER=3

MIX_POSITION_LAT=54.0236
MIX_POSITION_LNG=13.9047
MIX_POSITION_ZOOM=12
MIX_WEATHER_API_KEY=
MIX_WEATHER_API_URL="http://api.openweathermap.org/data/2.5/weather?lat=%LAT%&lon=%LNG%&lang=de&units=metric&APPID="
MIX_WEATHER_API_ICON_URL="http://openweathermap.org/img/w/%ICON%.png"
