<?php

namespace App\Http\Requests;

use Carbon\Carbon;
use Illuminate\Contracts\Validation\Validator;

class ConfigSaisonRentDatesRequest extends AdminRequest
{
    protected $modelName = 'ConfigSaisonRentDates';

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return auth()->user()->can('write ConfigSaisonRentDates');
    }

    protected function failedValidation(Validator $validator)
    {
        dd($validator->errors());
        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }

    /**
     * Get the validation rules that apply to the request.Customer
     *
     * @return array
     */
    public function rules()
    {
        $rules = [
            'config_saison_rent_id'  => 'required',
            'from'      => 'exclude_if:until,null|required|date|before:until',
            'until'     => ['required','date','after:from'],
            'holiday'   => '',
        ];

        return $rules;
    }
}
