<?php
return [
    'public' => [
        'items' => [
            'Dashboard'   => [
                'text'  => 'Dashboard',
                'title' => 'Dashboard',
                'icon'  => 'fas fa-home',
                'route' => 'public.dashboard',
                'hide_on_mobile' => false,
            ],
        ],
        'hide_on_mobile' => false,
    ],
    'customer' => [
        'items' => [
            'Dashboard'   => [
                'text'  => 'Dashboard',
                'title' => 'Dashboard',
                'icon'  => 'fas fa-home',
                'route' => 'public.dashboard',
                'hide_on_mobile' => false,
            ],
            'Daten'   => [
                'permissions'   => ['read ProfileMenu'],
                'icon'  => 'fas fa-ship',
                'hide_on_mobile' => false,
                'items' => [
                    [
                        'permissions'   => ['read Customer','write Customer'],
                        'text'  => 'Profile',
                        'title' => 'Profile',
                        'icon'  => 'fas fa-user',
                        'route' => 'customer.profile.index',
                        'hide_on_mobile' => false,
                    ],
                    [
                        'permissions'   => ['read Boat','write Boat'],
                        'text'  => 'Boots Daten',
                        'title' => 'Boots Daten',
                        'icon'  => 'fas fa-anchor',
                        'route' => 'customer.boats.index',
                        'hide_on_mobile' => false,
                    ],
                    [
                        'permissions'   => ['read BoatDates'],
                        'text'  => 'Rechnungen',
                        'title' => 'Rechnungen',
                        'icon'  => 'fas fa-concierge-bell',
                        'route' => 'customer.boatDates.index',
                        'hide_on_mobile' => false,
                    ],
                ],
            ],
            'Service Anfragen' => [
                'permissions'   => ['read ServiceMenu'],
                'icon'  => 'fas fa-ship',
                'hide_on_mobile' => false,
                'items' => [
                    [
                        'permissions'   => ['read ServiceRequest','write ServiceRequest'],
                        'text'  => 'Anfragen',
                        'title' => 'Anfragen',
                        'icon'  => 'fas fa-user',
                        'route' => 'customer.serviceRequests.index',
                        'hide_on_mobile' => false,
                    ],
                ],
            ],
        ],
        'hide_on_mobile' => false,
    ],
    'admin' => [
        'items' => [
            'Dashboard'   => [
                'text'  => 'Dashboard',
                'title' => 'Dashboard',
                'icon'  => 'fas fa-home',
                'route' => 'admin.dashboard',
                'hide_on_mobile' => false,
            ],
            'Caravans'   => [
                'permissions'   => ['read CaravansMenu'],
                'icon'  => 'fas fa-caravan',
                'hide_on_mobile' => false,
                'items' => [
                    [
                        'permissions'   => ['read Caravan', 'write Caravan'],
                        'text'  => 'Caravans',
                        'title' => 'Caravans',
                        'icon'  => 'fas fa-caravan',
                        'route' => 'admin.caravans.index',
                        'hide_on_mobile' => true,
                    ],
                    [
                        'permissions'   => ['read CaravanDates', 'write CaravanDates'],
                        'text'  => 'Caravan Rezeption',
                        'title' => 'Caravan Rezeption',
                        'icon'  => 'fas fa-concierge-bell',
                        'route' => 'admin.caravanDates.index',
                        'hide_on_mobile' => false,
                    ],
                ],
            ],
            'Boote'   => [
                'permissions'   => ['read BoatsMenu'],
                'icon'  => 'fas fa-ship',
                'hide_on_mobile' => false,
                'items' => [
                    [
                        'permissions'   => ['read Boat','write Boat'],
                        'text'  => 'Gäste',
                        'title' => 'Gäste',
                        'icon'  => 'fas fa-concierge-bell',
                        'route' => 'admin.boatGuests.index',
                        'hide_on_mobile' => true,
                    ],
                    [
                        'permissions'   => ['read Boat','write Boat'],
                        'text'  => 'Gäste Rezeption',
                        'title' => 'Gäste Rezeption',
                        'icon'  => 'fas fa-concierge-bell',
                        'route' => 'admin.boatGuestDates.index',
                        'hide_on_mobile' => false,
                    ],
                    [
                        'permissions'   => ['read Boat','write Boat'],
                        'text'  => 'Dauerlieger',
                        'title' => 'Dauerlieger',
                        'icon'  => 'fas fa-ship',
                        'route' => 'admin.boats.index',
                        'hide_on_mobile' => true,
                    ],
                    [
                        'permissions'   => ['read BoatDates','write BoatDates'],
                        'text'  => 'Saison Liegeplätze',
                        'title' => 'Saison Liegeplätze',
                        'icon'  => 'fas fa-anchor',
                        'route' => 'admin.boatDates.saison',
                        'hide_on_mobile' => false,
                    ],
                    [
                        'permissions'   => ['read BoatDates','write BoatDates'],
                        'text'  => 'Winterlager',
                        'title' => 'Winterlager',
                        'icon'  => 'fas fa-snowflake',
                        'route' => 'admin.boatDates.winter',
                        'hide_on_mobile' => false,
                    ],
                ],
            ],
            'Content'   => [
                'permissions'   => ['read ContentMenu'],
                'icon'  => 'fas fa-newspaper',
                'hide_on_mobile' => false,
                'items' => [
                    [
                        'permissions'   => ['read Page', 'write Page'],
                        'text'  => 'Pages',
                        'title' => 'Pages',
                        'icon'  => 'fas fa-file',
                        'route' => 'admin.pages.index',
                        'hide_on_mobile' => false,
                    ],
                    [
                        'permissions'   => ['read Widget', 'write Widget'],
                        'text'  => 'Widgets',
                        'title' => 'Widgets',
                        'icon'  => 'fas fa-newspaper',
                        'route' => 'admin.widgets.index',
                        'hide_on_mobile' => false,
                    ],
                ],
            ],
            'Permissions'   => [
                'permissions'   => ['read PermissionsMenu'],
                'icon'  => 'fas fa-user-lock',
                'hide_on_mobile' => false,
                'items' => [
                    [
                        'permissions'   => ['read User', 'write User'],
                        'text'  => 'Users',
                        'title' => 'Users',
                        'icon'  => 'fas fa-user',
                        'route' => 'admin.users.index',
                        'hide_on_mobile' => false,
                    ],
                    [
                        'permissions'   => ['read Role', 'write Role'],
                        'text'  => 'Roles',
                        'title' => 'Roles',
                        'icon'  => 'fas fa-user-tag',
                        'route' => 'admin.roles.index',
                        'hide_on_mobile' => false,
                    ],
                    [
                        'permissions'   => ['read Permission', 'write Permission'],
                        'text'  => 'Permissions',
                        'title' => 'Permissions',
                        'icon'  => 'fas fa-user-tag',
                        'route' => 'admin.permissions.index',
                        'hide_on_mobile' => false,
                    ],
                ],
            ],
            'Kunden'   => [
                'permissions'   => ['read CustomersMenu'],
                'icon'  => 'fas fa-user',
                'hide_on_mobile' => false,
                'items' => [
                    [
                        'permissions'   => ['read Customer', 'write Customer'],
                        'text'  => 'Dauerlieger',
                        'title' => 'Dauerlieger',
                        'icon'  => 'fas fa-user',
                        'route' => 'admin.customers.index',
                        'hide_on_mobile' => false,
                    ],
                    [
                        'permissions'   => ['read Customer', 'write Customer'],
                        'text'  => 'Gäste',
                        'title' => 'Gäste',
                        'icon'  => 'fas fa-concierge-bell',
                        'route' => 'admin.customers.guests',
                        'hide_on_mobile' => false,
                    ],
                ],
            ],
            'Services'   => [
                'permissions'   => ['read ServiceMenu'],
                'icon'  => 'fas fa-concierge-bell',
                'hide_on_mobile' => false,
                'items' => [
                    [
                        'permissions'   => ['read ServiceRequest', 'write ServiceRequest'],
                        'text'  => 'Service Anfragen',
                        'title' => 'Service Anfragen',
                        'icon'  => 'fas fa-pump-soap',
                        'route' => 'admin.serviceRequests.index',
                        'hide_on_mobile' => true,
                    ],
                    [
                        'permissions'   => ['read Material', 'write Material'],
                        'text'  => 'Material',
                        'title' => 'Material',
                        'icon'  => 'fas fa-pump-soap',
                        'route' => 'admin.materials.index',
                        'hide_on_mobile' => true,
                    ],
                    [
                        'permissions'   => ['read Service', 'write Service'],
                        'text'  => 'Service',
                        'title' => 'Service',
                        'icon'  => 'fas fa-pump-soap',
                        'route' => 'admin.services.index',
                        'hide_on_mobile' => true,
                    ],
                    [
                        'permissions'   => ['read ServiceCategory', 'write ServiceCategory'],
                        'text'  => 'Service Arten',
                        'title' => 'Service Arten',
                        'icon'  => 'fas fa-concierge-bell',
                        'route' => 'admin.serviceCategories.index',
                        'hide_on_mobile' => true,
                    ],
                    [
                        'permissions'   => ['read MaterialCategory', 'write MaterialCategory'],
                        'text'  => 'Material Arten',
                        'title' => 'Material Arten',
                        'icon'  => 'fas fa-concierge-bell',
                        'route' => 'admin.materialCategories.index',
                        'hide_on_mobile' => true,
                    ],
                ],
            ],
            'Info'   => [
                'permissions'   => ['read InfoMenu'],
                'icon'  => 'fas fa-info-circle',
                'hide_on_mobile' => false,
                'items' => [
                    [
                        'permissions'   => ['read Routes'],
                        'text'  => 'Routes',
                        'title' => 'Routes',
                        'icon'  => 'fas fa-route',
                        'route' => 'admin.infos.routes',
                        'hide_on_mobile' => false,
                    ],
                    [
                        'permissions'   => ['read Emojis'],
                        'text'  => 'Emojis',
                        'title' => 'Emojis',
                        'icon'  => 'fas fa-route',
                        'route' => 'admin.infos.emojis',
                        'hide_on_mobile' => true,
                    ],
                    [
                        'permissions'   => ['read Routes'],
                        'text'  => 'PHPInfo',
                        'title' => 'PHPInfo',
                        'icon'  => 'fas fa-info',
                        'route' => 'admin.infos.php',
                        'hide_on_mobile' => false,
                    ],
                ],
            ],
        ],
        'hide_on_mobile' => false,
    ],
];
