### Send request with dynamic variables in request's body
POST https://port.test/api/price/rentalDates
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Accept: application/json

{
    "from": "2023-07-01",
	"until": "2023-07-12",
    "customer_id": 13,
    "rentable_id": 1,
	"rentable_type": "apartment",
    "rental_cleaning": true,
    "kilowatt": true,
	"kilowatt_value": 2
}

###
