### Send request with dynamic variables in request's body
POST https://port.test/api/price/boatDates
Content-Type: application/json
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Accept: application/json

{
	"boat_id": 35,
	"modus": "summer",
	"from": "2023-05-01",
	"until": "2023-10-31",
	"crane": true,
	"mast_crane": true,
	"duration_mast_crane": 1,
	"cleaning": false,
	"transport": true,
	"length": 8.5,
	"width": 2.5,
	"weight": 3000,
	"mast_length": 9,
	"mast_weight": 70,
	"price": 0
}

###
