### Send request with dynamic variables in request's body
POST http://port.test/admin/boatDates/price/calculate
Content-Type: application/json

{
    "boat_id": 1,
    "from": "2022-06-01",
	"until": "2022-09-30",
	"crane": 1,
	"mast_crane": 1,
	"cleaning": 0,
	"modus": "saison",
	"length": 8.5,
    "width": 2.5,
    "weight": 3000,
    "mast_length": 9,
    "mast_weight": 70,
    "default_price": 0
}

###
