name: Dusk-Tests
on:
    push:
        branches: [ testing ]
    pull_request:
        branches: [ testing ]

jobs:
    Dusk-Test:
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mariadb:latest
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes
                    MYSQL_DATABASE: port_demo
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            - uses: actions/checkout@v2
            - name: Configure Application
              run: bin/ci
            - name: Configure Laravel Dusk
              run: bin/ci-dusk
            - name: Execute Dusk tests via PHPUnit
              run: php artisan pest:dusk --env=demo
